# @package _global_

model:
  _target_: main.module_controlnet.Model
  lr: 1e-4
  lr_beta1: 0.95
  lr_beta2: 0.999
  lr_eps: 1e-6
  lr_weight_decay: 1e-3
  cfg_dropout_prob: 0.1
  controlnet_dropout_prob: 0.2
  rms_window_size: 10000
  low_pass_window_size: 2000
  depth_factor: 0.2

